### PR TITLE
file input with FileReference

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Comment by burnout87** [comment]
image

**Comment by burnout87** [comment]
It generates a set of two radio buttons, which respectively enable/disable and hide/show the correspondent file upload input or textfield for the url. 

I also verified that the enabled field is the one actually providing the value to the form that will be submitted, so no conflict between the two available options.

**Review by volodymyrss — APPROVED** [review]
For me it's ok, but I don't know too much here. Do you have a live demo?

**Review by dsavchenko — APPROVED** [review]
Looks good for me, but I didn't try it live either. 
I think we should merge and see in staging.

**Pull request merged**
