### PR TITLE
setting default value url file_uploader

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Comment by dsavchenko** [comment]
What does it show for `POSIXPath` parameter? Does it still makes sense to preserve?

**Comment by burnout87** [comment]
> What does it show for `POSIXPath` parameter? Does it still makes sense to preserve?

It checks if it's a `FilreReference`

https://github.com/oda-hub/frontend-tab-generator/blob/fe156c570c6f0dc108b0bdeffb8a6c1fb12c4531/mmoda_tab_generator/templates/instr.inc#L3

**Comment by burnout87** [comment]
> But it's a superclass. Now I remember, both options have it as `owl_uri`. If it was FileURL originally, it's ok. If it was a `PosixPATH`, then it references to the local file in the repo/container (which is presumably there, but not guaranteed). 

So:

* if it's a `PosixPATH`, should it only shows the file-selector input?
* if it's a `FileURL` it should appears as now ? (option to choose a URL or a file to upload)

> This makes no sense in the frontend context, and I doubt it will even pass through the dispatcher. As far as we don't have the distinction of `owl_uri`s here, maybe we can just check if the default is URL and keep it only in this case

So, in case we have a URL in the default value (ie `$instrument_defaults['{{ par_name }}']`),   we don't show the file selector ?

**Comment by dsavchenko** [comment]
Almost contrary. I propose to always show the selector, but to keep the default value only if it's URL (which come from FileURL), otherwise leave it empty as before. 

Also, if there is a URL default, to have a selector to be in "URL" position by default. Otherwise, probably upload field is more appropriate. I hope it's not too complicated...

**Comment by burnout87** [comment]
> Almost contrary. I propose to always show the selector, but to keep the default value only if it's URL (which come from FileURL), otherwise leave it empty as before.
> 
> Also, if there is a URL default, to have a selector to be in "URL" position by default. Otherwise, probably upload field is more appropriate. I hope it's not too complicated...

Thanks for the clarification, it's already there, I will post later a couple of examples

**Comment by burnout87** [comment]
example

image

**Review by dsavchenko — APPROVED** [review]

**Pull request merged**
